---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: upgrade the distro
  apt: upgrade=yes

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - vim
    - curl
    - gnupg
    - rsync
    - wget
    - gcc
    - ack-grep
    - checkinstall
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libreadline6-dev
    - libc6-dev
    - libssl-dev
    - libmysql++-dev
    - libpq-dev
    - libicu-dev
    - libyaml-dev
    - libgdbm-dev
    - libncurses5-dev
    - libffi-dev
    - logrotate
    - make
    - build-essential
    - zlib1g-dev
    - openssh-server
    - libyaml-dev
    - postfix
