---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx

- name: copy nginx default conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: copy nginx default site
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx

- name: copy nginx gitlab_ci site
  template: src=gitlab_ci.conf.j2 dest=/etc/nginx/sites-available/gitlab_ci.conf
  notify: reload nginx

- name: enable nginx gitlab_ci site
  file: src=/etc/nginx/sites-available/gitlab_ci.conf dest=/etc/nginx/sites-enabled/gitlab_ci.conf state=link
  notify: reload nginx
