---
- name: Install GitLab CI
  hosts: gitlab-server
  vars_files:
    - roles/gitlab_vars.yml

  roles:
    - common
    - ruby
    - git
    - redis
    - mysql
    - python
    - gitlab_shell
    - gitlab
    - gitlab_ci
    - gitlab_runners
    - nginx
